### ISSUE TITLE
Title: CellRanger-ARC for Arbidosis failed with error

### ISSUE THREAD

**Issue by nilesh-iiita** [10XGenomics/cellranger-atac#7]
I am running CellRanger-ARC for Arabidopsis and I am getting the following error:

```
2023-06-02 14:40:02 [runtime] (failed)          ID.D3.SC_ATAC_GEX_COUNTER_CS.SC_ATAC_GEX_COUNTER._SC_ATAC_GEX_ANALYZER._PEAK_ANNOTATOR.ANNOTATE_PEAKS

[error] Pipestance failed. Error log at:
D3/SC_ATAC_GEX_COUNTER_CS/SC_ATAC_GEX_COUNTER/_SC_ATAC_GEX_ANALYZER/_PEAK_ANNOTATOR/ANNOTATE_PEAKS/fork0/join-uc5dd7a4574/_errors

Log message:
Traceback (most recent call last):
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 659, in _main
stage.main()
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 629, in main
lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 589, in _run
cmd()
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/external/martian/adapters/python/martian_shell.py", line 629, in <lambda>
lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/mro/atac/stages/analysis/annotate_peaks/init.py", line 105, in join
gene_id_name_map = build_gene_id_name_map(ref_mgr)
File "/data/rc/apps/rc/software/CellRanger-ARC/2.0.0/mro/atac/stages/analysis/annotate_peaks/init.py", line 60, in build_gene_id_name_map
fields.attrs.get("gene_name", fields.attrs["gene_id"])
File "pybedtools/cbedtools.pyx", line 392, in pybedtools.cbedtools.Interval.attrs.get
File "pybedtools/cbedtools.pyx", line 180, in pybedtools.cbedtools.Attributes.init
ValueError: need more than 1 value to unpack
```

I have tried the following to resolve the issue:

I have updated CellRanger-ARC to the latest version.
I have checked the input data to make sure that it is in the correct format.
I have checked the software used to run CellRanger-ARC to make sure that it is up to date and that it has all of the necessary dependencies.
I am still unable to resolve the issue.

Please help me to troubleshoot this issue.

Thank you.

**Comment by nilesh-iiita** [comment]
[Solved](https://github.com/10XGenomics/cellranger/issues/220#issuecomment-1587596884)
